name: ueo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  cloudinary_public: ^0.23.0
  image_picker: ^1.2.1
  cloud_firestore: ^6.1.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  camera: ^0.11.3
  path_provider: ^2.1.5
  path: ^1.9.1
  pdf: ^3.11.1
  printing: ^5.13.6
  carousel_slider: ^5.1.1
  circular_bottom_navigation: ^2.4.0
  intl: ^0.19.0
  flutter_stripe: ^12.1.1
  dio: ^5.9.0
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^16.1.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_nav_bar: ^5.0.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/b.jpg
    - assets/back.png
    - assets/img.png
    - assets/background.png
    - assets/splash.png
    - assets/splash.jpeg
    - assets/sport.jpg
    - assets/Technology.jpg
    - assets/workshops.jpg
    - assets/food.jpg
    - assets/music.jpg
    - assets/bussiness.jpg
